tmux:
  symbols:
    branch: " "
    hashprefix: " "
    ahead: "󰁝 "
    behind: "󰁅 "
    staged: "󰵹 "
    conflict: " "
    modified: " "
    untracked: "󰆘 "
    stashed: "󰛴 "
    clean: "🔥 "
    insertions: " "
    deletions: " "
  styles:
    clear: "#[fg=#{@thm_fg}]"
    state: "#[fg=#{@thm_green},bold]"
    branch: "#[fg=#{@thm_green},bold]"
    remote: "#[fg=#{@thm_green}]"
    divergence: "#[fg=#{@thm_green}]"
    staged: "#[fg=#{@thm_green},bold]"
    conflict: "#[fg=#{@thm_green},bold]"
    modified: "#[fg=#{@thm_green},bold]"
    untracked: "#[fg=#{@thm_green},bold]"
    stashed: "#[fg=#{@thm_green},bold]"
    clean: "#[fg=#{@thm_green},bold]"
    insertions: "#[fg=#{@thm_green}]"
    deletions: "#[fg=#{@thm_green}]"
  layout: [branch, divergence, flags]
  options:
    hide_clean: false
    divergence_space: true
