exec-once = [workspace special:Messaging silent] uwsm app -- slack
exec-once = [workspace special:AI silent] claude
exec-once = [workspace special:Obsidian silent] uwsm app -- obsidian -disable-gpu --enable-wayland-ime
exec-once = [workspace special:Spotify silent] spotify
exec-once = [workspace special:DeskThing silent] deskthing
exec-once = [workspace special:forge silent] ghostty -e tmux new-session -A -s forge
exec-once = [workspace special:forge silent] ghostty -e bash -c 'tmux new-session -d -s job-applier -c /home/paulmv/Projects/Automations/job-applier && tmux split-window -h -t job-applier:1 -c /home/paulmv/Projects/Automations/job-applier && tmux send-keys -t job-applier:1.2 "nvim config/settings.py" Enter && tmux select-pane -t job-applier:1.1 && tmux attach -t job-applier'

exec-once = workspace = special:forge, fullscreen

exec-once = ~/.config/hypr/startup-webapps.sh
exec-once = ~/.config/hypr/group-workspaces.sh

exec-once = hyprctl setcursor Bibata-Modern-Class 24
