# Extra env variables
# env = MY_GLOBAL_ENV,setting

# Screenshot and screen recording output directories
env = OMARCHY_SCREENSHOT_DIR,$HOME/Pictures/Screenshots
env = OMARCHY_SCREENRECORD_DIR,$HOME/Videos/Screen Recordings
