auto_focus = true
mouse = true
editor = "nvim"
status = "default"
hide_blocked_users = true
show_attachment_links = true
autocomplete_limit = 20
messages_limit = 50

[markdown]
enabled = true
theme = "catppuccin-mocha"

[help]
compact_modifiers = true
padding = [1, 1]
separator = " • "

[picker]
width = 80
height = 25

[timestamps]
enabled = true
format = "3:04PM"

[date_separator]
enabled = true
format = "January 2, 2006"
character = "─"

[notifications]
enabled = true
duration = 0

[notifications.sound]
enabled = true
only_on_ping = true

[typing_indicator]
send = true
receive = true

[sidebar.markers]
expanded = "▾ "
collapsed = "▸ "
leaf = ""

[sidebar.indents]
dm = 2
group_dm = 1
guild = 2
category = 1
channel = 2
forum = 2

[icons]
guild_category = "󰯉 "
guild_text = "󰭻 "
guild_voice = "󰗋 "
guild_stage_voice = "󰗋 "
guild_announcement_thread = "󱂖 "
guild_public_thread = "󱇫 "
guild_private_thread = " "
guild_announcement = "󱂖 "
guild_forum = "󰊌 "
guild_store = " "

[keybinds]
toggle_guilds_tree = "`"
toggle_channels_picker = "alt+c"
toggle_help = "alt+?"
focus_guilds_tree = "alt+g"
focus_messages_list = "alt+m"
focus_message_input = "/"
focus_previous = "shift+tab"
focus_next = "tab"
suspend = "ctrl+z"
quit = "ctrl+c"
logout = "alt+0"

[keybinds.picker]
cancel = "esc"
up = "alt+p"
down = "alt+n"
top = "home"
bottom = "end"
select = "enter"

[keybinds.guilds_tree]
up = "k"
down = "j"
top = "g"
bottom = "G"
select_current = "enter"
yank_id = "i"
collapse_all = "_"
collapse_parent_node = "-"
move_to_parent_node = "p"

[keybinds.messages_list]
select_up = "k"
select_down = "j"
select_top = "g"
select_bottom = "G"
scroll_up = "K"
scroll_down = "J"
select_reply = "s"
reply = "R"
reply_mention = "r"
cancel = "esc"
edit = "e"
delete = "D"
delete_confirm = "d"
open = "o"
yank_content = "y"
yank_url = "u"
yank_id = "i"

[keybinds.message_input]
paste = "ctrl+v"
send = "enter"
cancel = "esc"
tab_complete = "`"
undo = "ctrl+u"
open_editor = "delete"
open_file_picker = "alt+f"

[keybinds.mentions_list]
up = "alt+p"
down = "alt+n"
top = "home"
bottom = "end"

[theme.title]
alignment = "left"
normal_style = { attributes = "dim" }
active_style = { foreground = "#cba6f7", attributes = "bold" }

[theme.footer]
alignment = "left"
normal_style = { attributes = "dim" }
active_style = { foreground = "#a6e3a1", attributes = "bold" }

[theme.border]
enabled = true
padding = [0, 0, 1, 1]
normal_style = { attributes = "dim" }
active_style = { foreground = "#cba6f7", attributes = "bold" }
normal_set = "round"
active_set = "round"

[theme.guilds_tree]
auto_expand_folders = true
graphics = true
graphics_color = "#7f849c"
online_style = { foreground = "#a6e3a1" }
idle_style = { foreground = "#f9e2af" }
dnd_style = { foreground = "#f38ba8" }
offline_style = { foreground = "#7f849c" }

[theme.scroll_bar]
visibility = "auto"
glyph_set = "unicode"
track_style = { attributes = "dim" }
thumb_style = { foreground = "#cba6f7" }

[theme.messages_list]
reply_indicator = ">"
forwarded_indicator = "<"
author_style = { foreground = "#f5e0dc", attributes = "bold" }
mention_style = { foreground = "#89b4fa", attributes = "bold" }
emoji_style = { foreground = "#a6e3a1" }
url_style = { foreground = "#89b4fa" }
attachment_style = { foreground = "#f9e2af" }
message_style = { foreground = "#cdd6f4" }
selected_message_style = { attributes = "reverse" }

[theme.messages_list.embeds]
provider_style = { foreground = "#7f849c", attributes = ["dim", "italic"] }
author_style = { foreground = "#bac2de", attributes = "italic" }
title_style = { foreground = "#89b4fa", attributes = "bold" }
description_style = { foreground = "#cdd6f4", attributes = "dim" }
field_name_style = { foreground = "#f9e2af", attributes = [
  "bold",
  "underline",
] }
field_value_style = { foreground = "#cdd6f4" }
footer_style = { foreground = "#7f849c", attributes = ["dim", "italic"] }
url_style = { foreground = "#89b4fa", underline = "solid" }

[theme.mentions_list]
min_width = 20
max_height = 0

[theme.dialog]
style = { foreground = "#cdd6f4" }
background_style = { attributes = "dim" }

[theme.help]
short_key_style = { foreground = "#7f849c" }
short_desc_style = { foreground = "#cdd6f4" }
full_key_style = { foreground = "#7f849c" }
full_desc_style = { foreground = "#cdd6f4" }
